const themes={usa250:{title:'USA250',sub:'Liberty Celebration',badge:'AMERICA 250',a:'#B23A48',b:'#102B5C',c:'#F6C653'},webexone:{title:'WebexOne',sub:'Drone Show Activated',badge:'AUSTIN 2026',a:'#FFD400',b:'#07111f',c:'#39D2FF'},flgisa:{title:'FLGISA',sub:'Florida Hero',badge:'FLORIDA HERO',a:'#2ECC71',b:'#07351F',c:'#F6C653'},mlb:{title:'MLB',sub:'Game Day Experience',badge:'GAME DAY',a:'#2E86DE',b:'#061A33',c:'#F6C653'},nba:{title:'NBA',sub:'All-Star Experience',badge:'ALL STAR',a:'#C8102E',b:'#101A33',c:'#F6C653'}};
const $=id=>document.getElementById(id);
const canvas=$('overlayCanvas'),ctx=canvas.getContext('2d');
const nameInput=$('nameInput'),nickInput=$('nickInput'),companyInput=$('companyInput'),eventInput=$('eventInput'),styleInput=$('styleInput'),imageInput=$('imageInput'),fileInput=$('fileInput');
const veytecToggle=$('veytecToggle'),webexToggle=$('webexToggle'),qrToggle=$('qrToggle'),renderBtn=$('renderBtn'),downloadBtn=$('downloadBtn'),statusEl=$('status'),themeInfo=$('themeInfo');
let currentDataUrl=null,uploadedUrl=null,lastImg=null;
function q(){return new URLSearchParams(location.search)}
function txt(el,f=''){return String((el&&el.value)||f).trim()}
function theme(){return themes[eventInput.value]||themes.usa250}
function status(m,c=''){statusEl.textContent=m;statusEl.className='status '+c}
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function fit(s,max,start,min=28){let z=start;do{ctx.font=`900 ${z}px Arial`;if(ctx.measureText(s).width<=max)break;z-=3}while(z>min);return z}
function cover(img,x,y,w,h){const ir=img.width/img.height,r=w/h;let sx=0,sy=0,sw=img.width,sh=img.height;if(ir>r){sw=img.height*r;sx=(img.width-sw)/2}else{sh=img.width/r;sy=(img.height-sh)/2}ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
function loadImage(src){return new Promise((res,rej)=>{if(!src)return res(null);const im=new Image();im.crossOrigin='anonymous';im.onload=()=>res(im);im.onerror=()=>rej(Error('Image could not load. Use file upload if the image URL blocks canvas.'));im.src=src})}
function info(){const t=theme(),s=styleInput.value;themeInfo.innerHTML=`<div class="theme-card"><b>${t.title}</b><span>${t.sub}<br>${t.badge}<br>Style: ${s.toUpperCase()}</span><div class="swatch" style="background:linear-gradient(135deg,${t.a},${t.b});box-shadow:inset 0 0 0 2px ${t.c}66"></div></div>`}
function sample(t){const g=ctx.createLinearGradient(0,0,1080,1620);g.addColorStop(0,t.b);g.addColorStop(1,'#030711');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1620);ctx.fillStyle=t.a+'55';ctx.beginPath();ctx.arc(540,700,330,0,7);ctx.fill();ctx.fillStyle=t.c;ctx.font='900 82px Georgia';ctx.textAlign='center';ctx.fillText(t.title,540,670);ctx.font='700 36px Arial';ctx.fillStyle='rgba(255,255,255,.8)';ctx.fillText('Upload or paste an image',540,735)}
function drawQR(t){if(!qrToggle.checked)return;ctx.fillStyle='white';rr(845,1248,135,135,15);ctx.fill();ctx.fillStyle=t.b;for(let r=0;r<7;r++)for(let c=0;c<7;c++)if((r+c+c*r)%3===0)ctx.fillRect(863+c*15,1266+r*15,10,10);ctx.font='800 15px Arial';ctx.textAlign='center';ctx.fillText('SCAN',912,1402)}
function brand(){ctx.font='900 23px Arial';ctx.textBaseline='middle';if(veytecToggle.checked){ctx.textAlign='left';ctx.fillStyle='rgba(255,255,255,.86)';ctx.fillText('VEYTEC',86,1542)}if(webexToggle.checked){ctx.textAlign='right';ctx.fillStyle='rgba(255,255,255,.78)';ctx.fillText('POWERED BY WEBEX',994,1542)}}
function frameClassic(t,name,nick,company){ctx.fillStyle='rgba(0,0,0,.72)';rr(90,86,900,155,20);ctx.fill();ctx.strokeStyle=t.c;ctx.lineWidth=4;rr(90,86,900,155,20);ctx.stroke();ctx.font=`900 ${fit(name,810,64)}px Arial`;ctx.textAlign='center';ctx.fillStyle='white';ctx.fillText(name,540,nick?150:178);if(nick){ctx.font='700 34px Georgia';ctx.fillStyle=t.c;ctx.fillText('“'+nick+'”',540,210)}ctx.fillStyle='rgba(0,0,0,.74)';rr(125,1365,830,120,18);ctx.fill();ctx.fillStyle=t.c;ctx.font='900 31px Arial';ctx.fillText(t.title+' · '+t.sub,540,1412);if(company){ctx.font='800 29px Arial';ctx.fillStyle='rgba(255,255,255,.85)';ctx.fillText(company,540,1455)}}
function frameDeluxe(t,name,nick,company){ctx.fillStyle=t.a;rr(58,58,964,92,24);ctx.fill();ctx.fillStyle=t.b;rr(76,76,928,56,16);ctx.fill();ctx.fillStyle=t.c;ctx.font='900 30px Arial';ctx.textAlign='center';ctx.fillText(t.badge,540,114);ctx.fillStyle='rgba(0,0,0,.82)';rr(70,1185,940,280,32);ctx.fill();ctx.strokeStyle=t.c;ctx.lineWidth=6;rr(70,1185,940,280,32);ctx.stroke();ctx.font=`900 ${fit(name,820,78,36)}px Arial`;ctx.fillStyle='white';ctx.fillText(name,540,1274);if(nick){ctx.font='700 42px Georgia';ctx.fillStyle=t.c;ctx.fillText('“'+nick+'”',540,1340)}ctx.font='900 34px Arial';ctx.fillStyle=t.a;ctx.fillText(t.title+' EXPERIENCE',540,1398);if(company){ctx.font='800 30px Arial';ctx.fillStyle='rgba(255,255,255,.84)';ctx.fillText(company,540,1438)}}
function frameHero(t,name,nick,company){ctx.fillStyle='rgba(0,0,0,.42)';ctx.fillRect(0,0,1080,1620);ctx.fillStyle=t.a;ctx.font='950 46px Arial';ctx.textAlign='center';ctx.fillText(t.badge,540,120);ctx.fillStyle='rgba(0,0,0,.84)';rr(55,1215,970,270,26);ctx.fill();ctx.strokeStyle=t.c;ctx.lineWidth=9;rr(55,1215,970,270,26);ctx.stroke();ctx.font=`950 ${fit(name,900,92,40)}px Arial`;ctx.fillStyle='white';ctx.fillText(name,540,1306);if(nick){ctx.font='700 48px Georgia';ctx.fillStyle=t.c;ctx.fillText('“'+nick+'”',540,1376)}ctx.font='900 34px Arial';ctx.fillStyle='rgba(255,255,255,.92)';ctx.fillText(t.title+' • '+t.sub,540,1432);if(company){ctx.font='900 30px Arial';ctx.fillStyle=t.a;ctx.fillText(company,540,1472)}}
function draw(img){const t=theme(),style=styleInput.value,name=txt(nameInput,'Guest Name').toUpperCase(),nick=txt(nickInput),company=txt(companyInput);ctx.clearRect(0,0,1080,1620);if(img)cover(img,0,0,1080,1620);else sample(t);let top=ctx.createLinearGradient(0,0,0,340);top.addColorStop(0,'rgba(0,0,0,.75)');top.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=top;ctx.fillRect(0,0,1080,340);let bot=ctx.createLinearGradient(0,1080,0,1620);bot.addColorStop(0,'rgba(0,0,0,0)');bot.addColorStop(.7,'rgba(0,0,0,.82)');bot.addColorStop(1,'rgba(0,0,0,.95)');ctx.fillStyle=bot;ctx.fillRect(0,1080,1080,540);ctx.strokeStyle=style==='classic'?t.c:t.a;ctx.lineWidth=style==='hero'?14:9;rr(38,38,1004,1544,36);ctx.stroke();ctx.strokeStyle=t.c;ctx.lineWidth=3;rr(68,68,944,1484,24);ctx.stroke();if(style==='classic')frameClassic(t,name,nick,company);else if(style==='hero')frameHero(t,name,nick,company);else frameDeluxe(t,name,nick,company);drawQR(t);brand();currentDataUrl=canvas.toDataURL('image/jpeg',.92);downloadBtn.disabled=false;status('Rendered '+t.title+' '+style,'ok')}
async function render(){try{status('Rendering...');lastImg=await loadImage(uploadedUrl||txt(imageInput));draw(lastImg)}catch(e){lastImg=null;draw(null);status(e.message,'err')}}
function download(){if(!currentDataUrl)return;const a=document.createElement('a');const safe=txt(nameInput,'vxp').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');a.href=currentDataUrl;a.download=`vxp-${eventInput.value}-${styleInput.value}-${safe||'collectible'}.jpg`;a.click()}
function boot(){const u=q();if(u.get('name'))nameInput.value=u.get('name');if(u.get('nick'))nickInput.value=u.get('nick');if(u.get('nickname'))nickInput.value=u.get('nickname');if(u.get('company'))companyInput.value=u.get('company');if(u.get('event')&&themes[u.get('event').toLowerCase()])eventInput.value=u.get('event').toLowerCase();if(u.get('style'))styleInput.value=u.get('style');if(u.get('image'))imageInput.value=u.get('image');info();renderBtn.onclick=render;downloadBtn.onclick=download;[nameInput,nickInput,companyInput,eventInput,styleInput,veytecToggle,webexToggle,qrToggle].forEach(el=>el.addEventListener('input',()=>{info();draw(lastImg)}));imageInput.onchange=()=>{uploadedUrl=null;render()};fileInput.onchange=()=>{const f=fileInput.files&&fileInput.files[0];if(!f)return;if(uploadedUrl)URL.revokeObjectURL(uploadedUrl);uploadedUrl=URL.createObjectURL(f);render()};render()}boot();